# Generated by Django 3.0.3 on 2021-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationDetails',
            fields=[
                ('station_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('fname', models.CharField(default=None, max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
