# Generated by Django 3.0.3 on 2021-04-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainno', models.CharField(max_length=10, unique=True)),
                ('fromstation', models.CharField(max_length=255, null=True)),
                ('tostation', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
