# Generated by Django 3.2 on 2021-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
