# Generated by Django 3.2 on 2021-06-18 13:42

from django.db import migrations, models
import main.models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ticket_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.FileField(blank=True, null=True, storage=main.storage.OverwriteStorage(), upload_to=main.models.uid_directory_path),
        ),
    ]
