# Generated by Django 3.2 on 2021-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='boarded',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
